name: Run Tests with JaCoCo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jacoco:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # or 11 depending on your project

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests and generate JaCoCo report
        run: ./gradlew check

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/jacocoTestReport/html/